// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARZkLb5sGUwmNXYTA_03E8m6qV6l0uJKs',
    appId: '1:185095723104:web:6666287ea6fd83924a0b05',
    messagingSenderId: '185095723104',
    projectId: 'flutterauth2023',
    authDomain: 'flutterauth2023.firebaseapp.com',
    storageBucket: 'flutterauth2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe131_AGEHE5z0ntJYhjHGCyKfm48FshQ',
    appId: '1:185095723104:android:4a71a19c8152f1b54a0b05',
    messagingSenderId: '185095723104',
    projectId: 'flutterauth2023',
    storageBucket: 'flutterauth2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ2xggLdmOL_qFGG7Ya8trOZXJ_X_YTLU',
    appId: '1:185095723104:ios:9922571356c75d794a0b05',
    messagingSenderId: '185095723104',
    projectId: 'flutterauth2023',
    storageBucket: 'flutterauth2023.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ2xggLdmOL_qFGG7Ya8trOZXJ_X_YTLU',
    appId: '1:185095723104:ios:afc9a67525a786174a0b05',
    messagingSenderId: '185095723104',
    projectId: 'flutterauth2023',
    storageBucket: 'flutterauth2023.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
